<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'name' => fake()->name(),
            'email' => fake()->unique()->safeEmail(),
            'email_verified_at' => now(),
            'password' => static::$password ??= Hash::make('password'),
            'remember_token' => Str::random(10),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }

    /**
     * Создать пользователя с автогенерированными данными для авторегистрации
     */
    public function autoGenerated(array $attributes = []): static
    {
        return $this->state(function (array $attributes) {
            $generated = [];

            // Генерируем name если не передан
            if (empty($attributes['name'])) {
                $generated['name'] = $this->generateUniqueName();
            }

            // Генерируем email если не передан
            if (empty($attributes['email'])) {
                $generated['email'] = $this->generateUniqueEmail();
            }

            // Устанавливаем роль по умолчанию если не передана
            if (empty($attributes['role'])) {
                $generated['role'] = 'user';
            }

            return array_merge($generated, $attributes);
        });
    }

    /**
     * Создать пользователя только с Telegram данными
     */
    public function telegramOnly(array $attributes = []): static
    {
        return $this->autoGenerated(array_merge([
            'telegram_id' => $attributes['telegram_id'] ?? fake()->unique()->numerify('##########'),
            'telegram_username' => $attributes['telegram_username'] ?? fake()->unique()->userName(),
        ], $attributes));
    }

    /**
     * Создать пользователя без пароля (для авторегистрации)
     */
    public function withoutPassword(array $attributes = []): static
    {
        return $this->state(fn (array $attributes) => [
            'password' => null,
        ]);
    }

    /**
     * Генерировать уникальное имя пользователя
     */
    private function generateUniqueName(): string
    {
        $baseName = 'User_' . Str::random(6);
        $counter = 1;
        $name = $baseName;

        // Проверяем уникальность имени
        while (\App\Models\User::where('name', $name)->exists()) {
            $name = $baseName . '_' . $counter;
            $counter++;
        }

        return $name;
    }

    /**
     * Генерировать уникальный email
     */
    private function generateUniqueEmail(): string
    {
        $baseEmail = 'user_' . Str::random(8) . '@autogenerated.local';
        $counter = 1;
        $email = $baseEmail;

        // Проверяем уникальность email
        while (\App\Models\User::where('email', $email)->exists()) {
            $email = 'user_' . Str::random(8) . '_' . $counter . '@autogenerated.local';
            $counter++;
        }

        return $email;
    }
}
